### ISSUE TITLE
Markdown files and documentation structure

### ISSUE THREAD

**Issue by hdolfen** [pyfsi/coconut#11]
I think it may be useful to put a .md file in the coupling_components folder. This would be the highest level in the documentation about the use of CoCoNuT and is typically the place were the framework is entered (via analysis.py). Some general explanation can be given here, followed by some specific things. I think this would be a more logical "front page" of the documentation website, now the "CouplingComponents" tab opens the page of "CoupledSolvers".

I would explain how the analysis.py file works, because this is typically the script someone will use to start a simulation. A bit of explanation about tools.py, component.py and interface.py could also be useful.

Furthermore this is the logical location to explain the `number_of_timesteps` setting. Its meaning is of course self-evident, but for a new user it is not obvious what its value should be for a steady simulation.

Maybe you find this an overkill, it's just a suggestion. The page should not necessarily be very long either.

**Comment by nicolasdlss** [comment]
I agree with you. That would be a good addition to the website and the documentation in general.

**Comment by toondm** [comment]
For reference, this is the structure of the current website (as found in the file `coconut/docs/mkdocs.yml`):

![image](https://user-images.githubusercontent.com/52496830/92921362-34d3e480-f434-11ea-9a44-70c497668152.png)

For a new structure, I propose: 

    General *
    Overview of the code *
    Coupling components *
        Coupled solvers
            ...
        Predictors
        Convergence criteria
        Solver wrappers
            ...
        Mappers
    Data structure *
    Documentation
    Test examples
    Tests *

The starred ones are MarkDown files that don't exist yet.
-   `General` should contain a section `Introduction`, then comments about installation (exists already), then a `Getting started`. `Introduction` should contain a general overview of how the coconut code works, without going into specifics, mostly the philosophy but keep it quite short. `Getting started` should contain a kind of tutorial that goes over one of the test cases and explains more or less step-by-step how you run it, and what happens when you run it. 
-   `Overview of the code` gives overview of the 5 main folders in coconut, the rest of the website follows these folders. Some details are given about what is in each folder (coupling_components, data_structure, docs, test_examples, tests). 
-   `Coupling components` is a general overview page where you first explain the `Component` class which all other coupling components inherit from. It also explains some special objects like `Analysis` and `Interface`, and perhaps the tools too.
-   `Data structure` speaks for itself I guess. 
For some of these, I think we should wait until we get a new data structure, but we can already create the MarkDown files to have a good structure for the website. 
-   `Tests` gives an explanation on how to run tests etc.

If you have better ideas (I'm sure you do!), please propose them below. Once we have the structure, I'll create the MarkDown files in a new coconut branch and we can assign people to the different files.

**Comment by ldlcour** [comment]
Looks good to me, I would maybe change the order of the final files slightly:
-Test examples
-Tests
-Data structure
-Documentation

This because mostly these kind of files are scrolled top to bottom and a typical user will be more interested in running a Test example than learning about the data structure and how to edit the documentation 

Concerning "tests" I am not 100% sure, I think these are things you would typically run just after installing the software, so maybe they should be moved there or the installation guide should contain a reference to these tests?

**Comment by nicolasdlss** [comment]
I can see where you're coming from, but the idea of the current order is to represent the main folder structure.
For me personally I'm fine with both approaches.

**Comment by toondm** [comment]
I found out that is not possible to assign an MD file to a section on the website, e.g. to "Coupling components". With section I mean a title that links to several MD files. Therefore I had to adapt the layout of the website a bit (see e.g. "General: coupling_components.md"). The current .yml file is now:

![image](https://user-images.githubusercontent.com/52496830/93207608-82fe2600-f75b-11ea-8c7d-a6470074c21f.png)

The following is a list of MD files (or parts of files) that must be written:

- README.md: 
	-	section Introduction
	-	section Getting started
	-	section Overview of the code: I moved this here, because otherwise we need a separate file. It's also logical that this is in the main README file in my opinion. 
-	coupling_components.md
-	convergence_criteria.md: this page already existed, but is still empty
-	data_structure.md: to be done after new data structure is finished
-	tests.md

I created these files, giving a short description of the envisaged content in each file, and pushed this to the new branch `documentation`. 
So, looking for volunteers here! Leave a comment if you want to write one of these files. 
Who knows, maybe Joris will organize another sweet Friday when this task gets finished! Or maybe that's just wishful thinking on my part... ;-)

**Comment by nicolasdlss** [comment]
Basic documentation on coupling components have been written. (Interfaces should maybe covered in more detail in the data_structure.md, once the new data structure is adopted.

**Comment by nicolasdlss** [comment]
Task division:

- README.md @toondm
- converergence_criteria.md @awbral 
- tests.md @navaneethkn (new data structure)

**Comment by toondm** [comment]
I have merged and deleted the old documentation branches (`documentation`, `fix-docs`), so everyone can now create his own new branch from master. This makes it easier to avoid merge conflicts.

**Comment by toondm** [comment]
(@awbral finished convergence criteria docs, but issue is not yet fully closed)
