### ISSUE TITLE
Modelpart names in Abaqus

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#153]
Currently, the surface and node set names in de input file of Abaqus need to be uppercase, because the modelpart name is cast to uppercase in the solver wrapper. This is done because upon importing an inp file into Abaqus, Abaqus does the same thing.

Either this should be mentioned more clearly in the documentation or lower case names should be allowed. Before choosing the latter, it should be checked that this option does not create other problems.

Same can be said with respect to spaces and underscores.

**Comment by hdolfen** [comment]
For the `interface_input` it must be upper-case for the USR (because the USR internally works uppercase). Therefore the `ModelPart` name is cast to uppercase in the solver-wrapper. https://github.com/pyfsi/coconut/blob/f1d34a99f3e27ae8c736d4fb73d20461cd9a4bd8/coupling_components/solver_wrappers/abaqus/abaqus.py#L61-L63

This is also done for the `interface_output`, as the node set names end up being uppercase in the _`.odb`_-files.
