### ISSUE TITLE
Plotting of the test_examples

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#5]
I would like to adjust the debug files in order to be able to easily plot the tube_examples.
This would be nice with respect to educational purposes, but also for debugging purposes.
Now, there is a variable `self.debug` in the solver wrappers which saves the out/input of the solver if the boolean is set on true. However, these files don't always have the most logical name or structure.

The use of these files should not be limited to the tube examples.
Therefore, the structure of these files could be:
- output structure solver: `output_displacement_timeX`
```
x-displacement  y-displacement  z-displacement
0.0                      0.0                      0.0
```
- output flow solver: `output_load_timeX`
```
pressure  x-traction  y-traction  z-traction
0.0           0.0             0.0             0.0
```
(possibly same for the input)
When initializing the solver a file should also be generated with the coordinates of the load points or nodes on the fluid-structure interface, in the same order as the output files: `output_coordinates`
```
x-coordinate  y-coordinate  z-coordinate
0.0                      0.0                      0.0
```
Based on these files, the correct points can be selected, ordered and used for plotting in a very generic way.

This may seem as a lot of work, but most of this has already been implemented. Still it will take some time to adjust everything.

**Comment by toondm** [comment]
Good idea to make this more general. 
Some more ideas:
- Perhaps we should create a subfolder in test_examples to collect this code in one place? Or perhaps move it elsewhere, because this also starts to sound a bit like a post-processing module. 
- If we make the input/output files very general, we could just pickle the relevant ModelParts or even Interfaces, saving some code in the solvers.

**Comment by ldlcour** [comment]
It's been a while since I had a look at detailed look at the code, but if I understand/remember correctly: 
The debug switch prevents that input and output files of the solvers are deleted by copying them to a file appended with TimeX_IterY where the "_IterY" is crucial to prevent overwriting of the files in later coupling iterations. 
Furthermore, you might also desire to know what CoCoNuT itself is "seeing" as data to verify that the Python read and write happen as you expect (but theoretically this is the same as input and output files)
To me this appears a bit as 2 debug levels
I've tried to put this a bit in a scheme:
![Diagram](https://user-images.githubusercontent.com/38917676/78355706-72dbfb00-75ae-11ea-9e5b-5f2fbd193e24.jpg)

Above the double horizontal line:
- Circles indicate first level of debugging. These files are created, but the debug switch should prevent these from being overwritten and keep them per iteration.
- Diamonds indicate second level of debugging. These files do not exist, but are a representation of what CoCoNuT sees. This level of debugging should thus create new files.

Below the double horizontal line: 
- Files need to be created once
- Ellipsoid files already exist as CoCoNuT needs to read these 
- Diamonds need to be created 
- Taking into account the possibility of permutations etc. I think a general way of displaying what is used for mapping might be difficult. So I suggest a third level of debugging where a randomly selected field is mapped and displayed on both grids (Fluid and structure) (As was possible in Tango)

Concerning the naming:
- I don't think we should use different names for the debug files than for the files that are created during the run as this might cause additional confusion.
- I do agree that probably we could use clearer names for the files (e.g. loadpoints instead of faces).   
- I don't think think we really need to attach e.g. "displacement" to output for Abaqus as  it is implied and the names might get quite long if you also need to append time step and iteration 


Additionally: 
If we want to do this, then we also have to agree one where in the loop "iteration 1" starts and where it stops for the naming of the files.

**Comment by nicolasdlss** [comment]
Thanks Lucas for the nice overview!

It might be beneficial to make a distinction between either debugging and visualization/post-processing.

- For post-processing it makes to pickle the interfaces generated in Python as Toon suggested, as data is already grouped nicely. These can easily be used for visualization in Python. I propose to do this on a level which was not given in Lucas's figure, namely in the coupled solver, after the mappers. An additional parameter could be given like "save_output", which results in a generating a pickled file(s) containing displacements and loads at the end of each time step. (I basically already used such an approach for testing the solvers)

- For debugging on the level of the circles 1, 2, 3, 4, it makes sense to copy files a Lucas proposed: making a copy of the files that are generated and then normally removed.These files are solely meant for developing the concerning solver wrapper and it seems fitting to activate this with a Boolean in the solver wrapper. This is basically the way it is done now, except that it is only done for the displacements. I agree that the names can be kept to avoid confusion, but clearer names might indeed be useful (some of the names are extracted from Tango, but are not very clear in CoCoNuT). These files can then be easily read and interpreted. 

- For debugging occurring on the level of the level of the diamonds A, B, C, D. one could save a pickled version of the interface object after each iteration or generate a text file with it. The former saves in lines of code, but debugging requires maybe a bit more effort because these files are not human readable.
Personally I think these files are not really necessary if you have the other debugging files. So I would suggest to stick with the first two points mentioned above.

With respect to where in the loop the first iteration starts:
Currently this is implemented as follows:
```
*** start iteration 1 ***
  predictor: x0
  yt0 = flow solver(x0)
  find y0 from yt0
  xt0 = structure solver(y0)
  r0 = xt0 - x0
*** start iteration 2 ***
  find x1 from xt0
  yt1 = flow solver(x1)
  find y1 from yt1
  xt1 = structure solver(y1)
  r1 = xt1 - x1
*** start iteration 3 ***
  find x2 from xt1
...
```
So every consecutive calculation of the flow and structure solver is seen as one iteration.
