### ISSUE TITLE
OpenFoam issues & improvements

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#66]
Remaining OpenFoam issues and improvements
- remove start_time, end_time and dt in json solver_wrapper settings and use delta_t and timestep_start from coupled solver
- tempDisp and lengthDisp appear outside of OF workingdirectory
- mkdir error message
- in the PimpleFoam and InterFoam folders: are there files which can be deleted, because they are generated on compilation?
- other prints prints to be removed in the future inside solver_wrapper
- update documentation of example and incorporate README
- make the name of the solverwrapper consistent with other solver wrappers
- calculation with OF causes a lot of files: 12 files per timestep per processor => 8 cores, 100 time steps ~= 10 000 files

**Comment by navaneethkn** [comment]
Writing as all the points in checklist format for tracking purpose:

- [ ] remove start_time, end_time and dt in json solver_wrapper settings and use delta_t and timestep_start from coupled solver.
- [ ] tempDisp and lengthDisp appear outside of OF workingdirectory.
- [ ] mkdir error message
- [ ] In the PimpleFoam and InterFoam folders: are there files which can be deleted, because they are generated on compilation?
- [ ] other prints prints to be removed in the future inside solver_wrapper
- [ ] update documentation of example and incorporate README.
- [ ] make the name of the solverwrapper consistent with other solver wrappers.
- [ ] calculation with OF causes a lot of files: 12 files per timestep per processor => 8 cores, 100 time steps ~= 10 000 files
