### ISSUE TITLE
Loading software on coconut runtime

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#74]
Currently, all software that is used by the different solver wrappers has to be preloaded in the terminal where the coconut simulation will be launched. This gives some issues, e.g.: 

-   Kratos & coconut require different Python versions, so that they cannot work in the same terminal. This was temporarily fixed by loading the Kratos module on runtime, based on a bash-command in parameters.json. 
-   Fluent (ANSYS) & OpenFOAM cannot be loaded together, something MPI-related throws an error when starting Fluent. This is not yet an issue, as we cannot couple these solvers at the moment, but could become one in the future.

Hence the idea to load the software for a specific solver-wrapper only on runtime. This would also give the user a clear location where to write system-specific commands to configure software and licenses.

**Comment by hdolfen** [comment]
I also already thought about giving each solver wrapper a config file where the system-specific commands stand to make the required software available. 

Did you already think of an implementation? Because excecuting system commands in Python is typically done in a subshell that is closed immediately afterwards. It is possible to set the environment of the parent shell with the `os.environ`, like in [this stackoverflow answer](https://stackoverflow.com/a/12708396/12533660). The lmod system also has a python implementation but I think it is maybe not a good idea to make coconut dependent on the presence of the module system ([see this thread on StackOverflow](https://stackoverflow.com/a/54212717/12533660)). Or would you just prepend the necessary commands each time a solver wrapper calls a solver? Maybe this last solution is the only viable one for this issue, as perhaps the other one also will have conflicts as the environments of the solver wrappers won't be separated, unless we find a way to associate with each solver wrapper a separate shell.

**Comment by toondm** [comment]
Conclusion from the meeting:

-   add a single configuration file to the root-folder that contains all these configurations, e.g. "software.json" or "config.json" or sth
-   the JSON file contains a number of keys, more specifically 1 per software-version (e.g. Fluent v2019R1); the key is similar to the ones we use in the other JSON files, e.g. "abaqus.v614" or "fluent.v2019R1"
-    the value is a string with commands to load the necessary software, e.g. "module load ANSYS_CFD/2019R1"; multi-line commands can be split with ";"
