### ISSUE TITLE
Tube tube flow tube ringmodel example

### ISSUE THREAD

**Issue by awbral** [pyfsi/coconut#85]
Dieter pointed out that an error occurred while running this example. It originated from the JSON files not being updated with the new data structure. That issue is solved now, however a second error occurs:

In the tube ringmodel solver, a ValueError for unphysical pressure is raised in the first iteration.

**Comment by nicolasdlss** [comment]
Yes that's true, I also noticed that the change did not come true, although I was quite certain to have changed it at some point.
The fact that you obtain a ValueError is due to the fact that this very simple solver is not able to deal with the sudden pressure increase. It basically crashes, because of an unphysical pressure. This solver does converges if a reasonable velocity change is applied on the inlet.

**Comment by toondm** [comment]
Good to hear that Dieter tried to run coconut! :D
