### ISSUE TITLE
pressure_traction_test for Fluent v2020R1 fails on cfdclu55

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#94]
`FAIL: test_pressure_traction (coconut.tests.solver_wrappers.fluent.test_v2020R1.TestSolverWrapperFluent2020R1Tube3D)`
----------------------------------------------------------------------
```
Traceback (most recent call last):
  File "/cfdfile2/data/fm/nicolas/python_packages/coconut/coconut/tests/solver_wrappers/fluent/test_v2019R1.py", line 314, in test_pressure_traction
    np.testing.assert_allclose(traction[0], traction[2], rtol=1e-11)
  File "/apps/SL6.3/Anaconda/2019.07/python3.7/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1501, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/apps/SL6.3/Anaconda/2019.07/python3.7/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 827, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-11, atol=0

 

Mismatch: 0.0217%
Max absolute difference: 3.33955086e-13
Max relative difference: 1.2415593e-11
 x: array([[-10.349147,  -8.341815,  -4.579155],
       [ 46.352385,   2.219764,   2.705838],
       [ 26.331443,  -7.791217,  -2.45801 ],...
 y: array([[-10.349147,  -8.341815,  -4.579155],
       [ 46.352385,   2.219764,   2.705838],
       [ 26.331443,  -7.791217,  -2.45801 ],...
```
----------------------------------------------------------------------

Test uses maximum number of cores on machine (in this case 24 cores).
For other Fluent versions the test does work.
Either tolerance should be lowered or number of cores limited.

**Comment by hdolfen** [comment]
I don't think it's literally an upper limit to the number of cores, but just choosing a value to make its behavior more consistent. It's of course difficult to know how much cores we can expect from a system different than ours...

**Comment by toondm** [comment]
Yeah, Henri also recently noticed that this kind of test is a bit dependent on the system, because max number of cores is used to get results fast. I originally ran the tests on 36 cores I think, so I suppose the upper limit doesn't matter. 2019R3 does behave differently when deforming the mesh, that is discussed in the documentation, but I didn't notice any differences in 2020R1... (see also our [docs](https://pyfsi.github.io/coconut/fluent/#v2019r3-1950)).

Currently, the convergence criteria is 1e-12 in Fluent, so I guess we should make the criteria in these tests a bit less stringent, e.g. 1e-10 to have some margin. Criteria for e.g. the coordinates can be left as they are, those are stricter.
